name: CI Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install API Gateway dependencies
        working-directory: ./api_gateaway
        run: npm ci

      - name: Install Identity Service dependencies
        working-directory: ./identity_services
        run: npm ci

      - name: Install Media Service dependencies
        working-directory: ./media-service
        run: npm ci

      - name: Install Post Service dependencies
        working-directory: ./post-service
        run: npm ci

      - name: Install Search Service dependencies
        working-directory: ./search-service
        run: npm ci